// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto

It has these top-level messages:
	Person
	AddressBook
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name   string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id     int32                 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Email  string                `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phones []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=protobuf.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_PhoneNumber) Reset()                    { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string            { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()               {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

// Our address book file is just one of these.
type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "protobuf.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "protobuf.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "protobuf.AddressBook")
	proto.RegisterEnum("protobuf.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x75, 0xd3, 0x74, 0x69, 0x27, 0x50, 0xe2, 0x20, 0x12, 0x8a, 0x87, 0x90, 0x53, 0x40, 0xd8,
	0x43, 0x15, 0x3c, 0x5b, 0x28, 0x28, 0x5a, 0x53, 0x16, 0xc5, 0x73, 0x42, 0x46, 0x0c, 0x6d, 0x32,
	0x4b, 0xd2, 0x1e, 0xfa, 0xef, 0x1e, 0x24, 0x9b, 0x55, 0x44, 0x7a, 0xda, 0x37, 0xf3, 0x1e, 0x6f,
	0xdf, 0x3c, 0x38, 0xcf, 0xcb, 0xb2, 0xa5, 0xae, 0x2b, 0x98, 0xb7, 0xca, 0xb4, 0xbc, 0x67, 0x9c,
	0xd8, 0xa7, 0x38, 0x7c, 0x24, 0x5f, 0x02, 0xe4, 0x86, 0xda, 0x8e, 0x1b, 0x44, 0xf0, 0x9b, 0xbc,
	0xa6, 0x48, 0xc4, 0x22, 0x9d, 0x6a, 0x8b, 0x71, 0x06, 0x5e, 0x55, 0x46, 0x5e, 0x2c, 0xd2, 0xb1,
	0xf6, 0xaa, 0x12, 0x2f, 0x60, 0x4c, 0x75, 0x5e, 0xed, 0xa2, 0x91, 0x15, 0x0d, 0x03, 0xde, 0x82,
	0x34, 0x9f, 0xdc, 0x50, 0x17, 0xf9, 0xf1, 0x28, 0x0d, 0x16, 0x57, 0xea, 0xc7, 0x5f, 0x0d, 0xde,
	0x6a, 0xd3, 0xd3, 0x2f, 0x87, 0xba, 0xa0, 0x56, 0x3b, 0xed, 0xfc, 0x0d, 0x82, 0x3f, 0x6b, 0xbc,
	0x04, 0xd9, 0x58, 0xe4, 0x02, 0xb8, 0x09, 0x15, 0xf8, 0xfb, 0xa3, 0x21, 0x1b, 0x62, 0xb6, 0x98,
	0x9f, 0xb6, 0x7e, 0x3d, 0x1a, 0xd2, 0x56, 0x97, 0x5c, 0xc3, 0xf4, 0x77, 0x85, 0x00, 0x72, 0x9d,
	0x2d, 0x1f, 0x9f, 0x57, 0xe1, 0x19, 0x4e, 0xc0, 0x7f, 0xc8, 0xd6, 0xab, 0x50, 0xf4, 0xe8, 0x3d,
	0xd3, 0x4f, 0xa1, 0x97, 0xdc, 0x41, 0x70, 0x3f, 0xb4, 0xb3, 0x64, 0xde, 0x62, 0x0a, 0xd2, 0x10,
	0x9b, 0x5d, 0x5f, 0x42, 0x7f, 0x48, 0xf8, 0xff, 0x37, 0xed, 0xf8, 0x42, 0x5a, 0xe2, 0xe6, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0xc8, 0xd0, 0x39, 0x5d, 0x01, 0x00, 0x00,
}
